// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEBk1vsQUbXyUuQDehRsRKWTOLDHz8QZc',
    appId: '1:1017566295274:web:713529bfe54c20becb5393',
    messagingSenderId: '1017566295274',
    projectId: 'push-notification-14cd2',
    authDomain: 'push-notification-14cd2.firebaseapp.com',
    storageBucket: 'push-notification-14cd2.firebasestorage.app',
    measurementId: 'G-7KFKWNMQSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTpajNk255WGqiKXD5Vv1oDZVW7GNMmBY',
    appId: '1:1017566295274:android:069cb9527a6bf421cb5393',
    messagingSenderId: '1017566295274',
    projectId: 'push-notification-14cd2',
    storageBucket: 'push-notification-14cd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzDk_dvJr_MupmpGZtLyHVnqEqtf3VVGg',
    appId: '1:1017566295274:ios:f84c58c8bcc12c2bcb5393',
    messagingSenderId: '1017566295274',
    projectId: 'push-notification-14cd2',
    storageBucket: 'push-notification-14cd2.firebasestorage.app',
    iosBundleId: 'com.example.gtribe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzDk_dvJr_MupmpGZtLyHVnqEqtf3VVGg',
    appId: '1:1017566295274:ios:f84c58c8bcc12c2bcb5393',
    messagingSenderId: '1017566295274',
    projectId: 'push-notification-14cd2',
    storageBucket: 'push-notification-14cd2.firebasestorage.app',
    iosBundleId: 'com.example.gtribe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEBk1vsQUbXyUuQDehRsRKWTOLDHz8QZc',
    appId: '1:1017566295274:web:0b5115d9fa9e5befcb5393',
    messagingSenderId: '1017566295274',
    projectId: 'push-notification-14cd2',
    authDomain: 'push-notification-14cd2.firebaseapp.com',
    storageBucket: 'push-notification-14cd2.firebasestorage.app',
    measurementId: 'G-D2Q5E0LBFZ',
  );
}
